[package]
name = "coin"
version = "0.0.1"
edition = "2021"
license = "license.md"

[dependencies]
ethnum = "1.5.0"
k256 = "0.13.4"
serde = { version = "1.0.214", features = ["derive"] }
sha3 = "0.10.8"
