[package]
name = "coin"
version = "0.0.0"
edition = "2021"

[dependencies]
ethnum = "1.5.0"
k256 = "0.13.4"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"
serde = { version = "1.0.214", features = ["derive"] }
sha3 = "0.10.8"
